### ISSUE TITLE
null value in optional field triggers and error

### ISSUE THREAD

**Issue by khanzadyan** [openintegrationhub/jdbc-component#7]
Select the DB PostgreSQL and use the action `upsertRowByPrimaryKey` and try to map in incoming data which contains different values among them `null`.

If an optional field receives a value `null` it will not regard this as an empty record but will give an error:
```
java.lang.ClassCastException: javax.json.JsonValue$1 cannot be cast to javax.json.JsonString
	at org.glassfish.json.JsonObjectBuilderImpl$JsonObjectImpl.getJsonString(JsonObjectBuilderImpl.java:194)
	at org.glassfish.json.JsonObjectBuilderImpl$JsonObjectImpl.getString(JsonObjectBuilderImpl.java:199)
	at io.elastic.jdbc.Utils.setStatementParam(Utils.java:128)
	at io.elastic.jdbc.QueryBuilders.Query.executeUpsert(Query.java:235)
	at io.elastic.jdbc.actions.UpsertRowByPrimaryKey.execute(UpsertRowByPrimaryKey.java:82)
	at io.elastic.sailor.impl.MessageProcessorImpl.processMessage(MessageProcessorImpl.java:68)
	at io.elastic.sailor.impl.MessageConsumer.handleDelivery(MessageConsumer.java:68)
	at com.rabbitmq.client.impl.ConsumerDispatcher$5.run(ConsumerDispatcher.java:149)
	at com.rabbitmq.client.impl.ConsumerWorkService$WorkPoolRunnable.run(ConsumerWorkService.java:100)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by zubairov** [comment]
@khanzadyan could you please give more information, e.g. which trigger and/or action you used when experiencing this issue?

**Comment by khanzadyan** [comment]
thank @zubairov for noticing and sorry for that. The description is updated.
